// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH2-UGb-31Mf8251iF-usnSfYQBVin4Bc',
    appId: '1:106461540603:web:d89993d7a94b69568e405e',
    messagingSenderId: '106461540603',
    projectId: 'pathway-jobs',
    authDomain: 'pathway-jobs.firebaseapp.com',
    storageBucket: 'pathway-jobs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBnikqV1SkgFrMCmHMVskV3pKFgk-xlF4',
    appId: '1:106461540603:ios:df409b677f9d7ac48e405e',
    messagingSenderId: '106461540603',
    projectId: 'pathway-jobs',
    storageBucket: 'pathway-jobs.firebasestorage.app',
    iosBundleId: 'com.example.pathwayJobs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH2-UGb-31Mf8251iF-usnSfYQBVin4Bc',
    appId: '1:106461540603:web:cbde79d4c4f8add98e405e',
    messagingSenderId: '106461540603',
    projectId: 'pathway-jobs',
    authDomain: 'pathway-jobs.firebaseapp.com',
    storageBucket: 'pathway-jobs.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxMFRPJO_njh7OVNGfI5aerGelzHpSaK4',
    appId: '1:106461540603:android:7579d3e015c8fd378e405e',
    messagingSenderId: '106461540603',
    projectId: 'pathway-jobs',
    storageBucket: 'pathway-jobs.firebasestorage.app',
  );

}