import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart'; // Import Firebase core
import 'firebase_options.dart'; // Import the autogenerated Firebase options

// Import Screens
import 'screens/home_screen.dart';
import 'screens/register_screen.dart';
import 'screens/jobs_screen.dart';
import 'screens/cv_builder_screen.dart';
import 'screens/premium_screen.dart';
import 'screens/admin_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized(); // Ensure initialization
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform, // Initialize Firebase
  );
  
  runApp(PathwayJobsApp());
}

class PathwayJobsApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Pathway Jobs',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),

      // Initial Screen
      initialRoute: '/',

      routes: {
        '/': (context) => HomeScreen(),
        '/register': (context) => RegisterScreen(),
        '/jobs': (context) => JobsScreen(),
        '/cv_builder': (context) => CVBuilderScreen(),
        '/premium': (context) => PremiumScreen(),
        '/admin': (context) => AdminScreen(),
      },
    );
  }
}